version: '3.7'

services:
  mongo:
    build:
      context: .
      dockerfile: stages/development/Dockerfile.mongo
    container_name: baseg_mongodb
    environment:
      MONGO_INITDB_DATABASE: "baseg_development"
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/baseg_mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_PASSWORD_FILE: /run/secrets/baseg_mongodb_password
      MONGO_USER: "admin"
    secrets:
      - baseg_mongodb_password
      - baseg_mongodb_root_password
    volumes:
      - mongo:/data/db
    network_mode: host

secrets:
  baseg_mongodb_password:
    file: ./stages/development/mongo/password
  baseg_mongodb_root_password:
    file: ./stages/development/mongo/root_password

volumes:
  mongo:
